name: docker-hub
on:
  push:
    branches:
      - main
  schedule:
    - cron: "1 0 * * *"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker-hub:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Install required packages
      - name: Install apt packages
        run: sudo apt-get install -y jq
      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v4
      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Run script that checks for new versions and triggers builds
      - name: Run build script
        run: ./script.sh fetch --verbose
      # Commit data.json file if changes detected
      - name: Commit data.json metadata file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update data.json file with new versions
          branch: main
          file_pattern: data.json
