name: docker-hub
on:
  push:
    branches: main
  schedule:
    - cron: '1 */24 * * *'
jobs:
  docker-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Install apt packages
        run: sudo apt-get install -y jq moreutils
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Fetch new versions, trigger build, upload images to Docker Hub
        run: ./script.sh fetch --verbose
